version: '2'
services:

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - data:/data

  spark-worker-2:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - data:/data

  spark-submit:
    image: localhost:5000/microbrewery:0.1
    container_name: mango
    volumes:
      - data:/data
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    ports:
      - "9000:8080"

volumes:
  data:
