version: '2'
services:

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./:/code
    working_dir: /code

  spark-worker-1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./:/code
    working_dir: /code

  spark-worker-2:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./:/code
    working_dir: /code

  spark-submit:
    image: bde2020/spark-submit
    command: "bash ./run-microbrew.sh"
    volumes:
      - ./:/code
    working_dir: /code
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    ports:
      - "9000:8080"
