#!/usr/bin/env bash

set -e -x -v

# navigate to mango parent directory, set in Jenkins
if [ -z "$WORKSPACE" ]
then
	echo "WORKSPACE variable is not set. Defaulting to current directory.."
	WORKSPACE="$(echo $PWD)"
fi
pushd ${WORKSPACE}

# unique identifier for conda env
PYTHON_UUID=$(uuidgen)

# function that deletes conda environments and temporary environments
function clean_up {
    set +x +v
    # deactivate and remove all mango associated conda envs
    source deactivate
    # delete conda env, if it exists
    conda remove -y --force --name mango-build-${PYTHON_UUID} --all || \
        echo "conda ENV mango-build-${PYTHON_UUID} does not exist"

    # delete tmp directories
    rm -rf ${MANGO_TMP_DIR}
    rm -rf ${MANGO_MVN_TMP_DIR}
    set -x -v
}
trap clean_up EXIT

# create a conda environment for python build, if necessary
python=3.6

set +x +v
conda create -y -q -c conda-forge -n mango-build-${PYTHON_UUID} python=${python} pip=19.3.1 jupyterlab=2.0.1
source activate mango-build-${PYTHON_UUID}
set -x -v

# install npm and node in the venv for mango-pileup
conda install -y nodejs

pushd ${WORKSPACE}/mango-pileup/bdgenomics/mango/js
npm install

npm run test
popd

# deactivate and remove the conda env
set +e +x
source deactivate
conda remove -y --name mango-build-${PYTHON_UUID} --all
set -e -x

# exist mango working directory
popd

echo
echo "All the tests passed"
echo
