#!/bin/bash -x

SCRIPT_DIR="$(cd `dirname $0`/..; pwd)"
# pull pileup submodule
echo "Fetching pileup.js submodule..."
git submodule init
git submodule update --recursive

# install pileup dependencies
pwd
echo "installing pileup.js ..."
cd "$SCRIPT_DIR"/mango-cli/src/main/webapp/resources/pileup.js
npm install

# build pileup
echo "building pileup.js ..."
cd "$SCRIPT_DIR"/mango-cli/src/main/webapp/resources/pileup.js
npm run build

# install pileup
echo "installing pileup.js ..."
cd "$SCRIPT_DIR"/mango-cli/src/main/webapp/resources/node_modules
npm install "$SCRIPT_DIR"/mango-cli/src/main/webapp/resources/pileup.js
