#!/bin/bash -x

# pull pileup submodule
echo "Fetching pileup.js submodule..."
git submodule init
git submodule update --recursive

# install pileup dependencies
pwd
echo "installing pileup.js ..."
cd mango-cli/src/main/webapp/resources/pileup.js
npm install

# build pileup
echo "building pileup.js ..."
npm run build


