#!/bin/bash -x

SCRIPT_DIR="$(cd `dirname $0`/..; pwd)"
# build pileup
echo "building pileup.js ..."
cd "$SCRIPT_DIR"/mango-cli/src/main/webapp/resources/pileup.js
npm run build

# install pileup
echo "installing pileup.js ..."
cd "$SCRIPT_DIR"/mango-cli/src/main/webapp/resources/node_modules
npm install "$SCRIPT_DIR"/mango-cli/src/main/webapp/resources/pileup.js
