#!/bin/bash -x

#build pileup
pwd
echo "building pileup.js ..."
cd mango-cli/src/main/webapp/resources/pileup.js
npm run build

# install pileup
pwd
echo "installing pileup.js ..."
cd ../node_modules
pwd
npm install ../pileup.js
