#!/usr/bin/env bash

set -e -x -v

# navigate to mango parent directory, set in Jenkins
if [ -z "$WORKSPACE" ]
then
	echo "WORKSPACE variable is not set. Defaulting to current directory.."
	WORKSPACE="$(echo $PWD)"
fi
pushd ${WORKSPACE}

# move to Scala 2.11 if requested
if [ ${SCALAVER} == 2.11 ];
then
    set +e
    ./scripts/move_to_scala_2.11.sh
    set -e
fi

# move to Spark 2.x if requested
if [ ${SPARK_VERSION} == 2.4.6 ];
then
    set +e
    ./scripts/move_to_spark_2.sh
    set -e
fi

# clean
mvn clean

# Push snapshot at https://oss.sonatype.org/content/repositories/snapshots/
mvn --settings=${SETTINGS_DOCKER} deploy -DskipTests -Pdistribution

