#!/usr/bin/env bash


# is a virtualenv active?
INVENV=$(python -c 'import sys; print ("1" if hasattr(sys, "real_prefix") else "0")')

if [[ "$INVENV" -ne 1 ]]; then
  echo "virtualenv is not active"
  exit 1
fi

# is SPARK_HOME set?
if [ -z "$SPARK_HOME" ]; then
    echo "You need to set SPARK_HOME"
    exit 1
fi

# is node.js install
if ! [ -x "$(command -v npm)" ]; then
    echo "You need to install node.js"
    exit 1
fi

# add pyspark to the python path
PY4J_ZIP="$(ls -1 "${SPARK_HOME}/python/lib" | grep py4j)"
export PYTHONPATH=${SPARK_HOME}/python:${SPARK_HOME}/python/lib/${PY4J_ZIP}:${PYTHONPATH}

# put mango jar on the pyspark path
ASSEMBLY_DIR="${PWD}/mango-assembly/target"
ASSEMBLY_JAR="$(ls -1 "$ASSEMBLY_DIR" | grep "^mango-assembly[0-9A-Za-z\_\.-]*\.jar$" | grep -v javadoc | grep -v sources || true)"
export PYSPARK_SUBMIT_ARGS="--jars ${ASSEMBLY_DIR}/${ASSEMBLY_JAR} --driver-class-path ${ASSEMBLY_DIR}/${ASSEMBLY_JAR} pyspark-shell"

# build executable
mvn clean package -DskipTests

# prepare mango python
pushd mango-python
make prepare
make develop
popd

# prepare mango viz
pushd mango-pileup
make prepare
make develop
popd
